[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
follow_symlink = false

# Enable data persistence with local PostgreSQL
data_persistence = true

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Authorize users to upload files with messages
multi_modal = true

# Allows user to use speech to text
[features.speech_to_text]
    enabled = false
    # See all languages here https://github.com/JamesBrill/react-speech-recognition/blob/HEAD/docs/API.md#language-string
    # language = "en-US"

# MCP (Model Context Protocol) configuration
[features.mcp]
    # Enable MCP support
    enabled = true

[features.mcp.sse]
    # Enable Server-Sent Events MCP connections
    enabled = true

[features.mcp.stdio]
    # Enable stdio MCP connections (for local commands)
    enabled = true
    # Allowed executables for security
    allowed_executables = ["npx", "uvx", "python"]

# MCP Server Configurations
[[features.mcp.servers]]
name = "simple_sse"
transport = "sse"
url = "http://mcp_server:8000/mcp/"

[[features.mcp.servers]]
name = "everything"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-everything"]

[UI]
# Name of the assistant.
name = "OpenAI Agents SDK Boilerplate"

# Description of the assistant.
description = "Multi-modal agentic AI boilerplate with OpenAI Agents SDK, Chainlit UI, and MCP integration"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
# github = "https://github.com/Chainlit/chainlit"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/test.css"

# Override default MUI light theme. (Check theme.ts)
[UI.theme.light]
    background = "#FAFAFA"
    paper = "#FFFFFF"

    [UI.theme.light.primary]
        main = "#4A90E2"
        dark = "#357ABD"
        light = "#6BA3E5"

# Override default MUI dark theme. (Check theme.ts)
[UI.theme.dark]
    background = "#1E1E1E"
    paper = "#2A2A2A"

    [UI.theme.dark.primary]
        main = "#4A90E2"
        dark = "#357ABD"
        light = "#6BA3E5"

[meta]
generated_by = "1.0.0"